version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Moq
    versions:
    - 4.15.2
    - 4.16.0
  - dependency-name: HtmlAgilityPack
    versions:
    - 1.11.29
  - dependency-name: Microsoft.Azure.WebJobs.Extensions.Storage
    versions:
    - 4.0.3
